/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'email' : string,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'clientName' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addPortfolioItem' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'addProduct' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<
    [string, string, string, Array<CartItem>],
    bigint
  >,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAboutUs' : ActorMethod<[], string>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCartItems' : ActorMethod<[], Array<CartItem>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getPortfolioItem' : ActorMethod<[bigint], PortfolioItem>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getShippingInfo' : ActorMethod<[], string>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'updateAboutUs' : ActorMethod<[string], undefined>,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    undefined
  >,
  'updateShippingInfo' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];