/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'email' : IDL.Text,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'clientName' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CartItem)],
      [IDL.Nat],
      [],
    ),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAboutUs' : IDL.Func([], [IDL.Text], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getPortfolioItem' : IDL.Func([IDL.Nat], [PortfolioItem], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getShippingInfo' : IDL.Func([], [IDL.Text], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'updateAboutUs' : IDL.Func([IDL.Text], [], []),
  'updatePortfolioItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateShippingInfo' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'email' : IDL.Text,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'clientName' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CartItem)],
        [IDL.Nat],
        [],
      ),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAboutUs' : IDL.Func([], [IDL.Text], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getPortfolioItem' : IDL.Func([IDL.Nat], [PortfolioItem], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getShippingInfo' : IDL.Func([], [IDL.Text], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'updateAboutUs' : IDL.Func([IDL.Text], [], []),
    'updatePortfolioItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateShippingInfo' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };