/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomDesignRequest {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : string,
  'description' : string,
  'fileUrls' : Array<string>,
  'productType' : string,
  'email' : string,
  'colorPreferences' : string,
  'chatEscalation' : boolean,
}
export interface IntegrationSettings {
  'printifyShopId' : string,
  'shopifyDomain' : string,
  'printifyApiKey' : string,
  'shopifyApiToken' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'trackingNumber' : string,
  'createdAt' : string,
  'email' : string,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : bigint, 'quantity' : bigint }
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'clientName' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Product {
  'id' : bigint,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomDesignRequest' : ActorMethod<
    [string, string, string, string, string, Array<string>, string, boolean],
    bigint
  >,
  'addPortfolioItem' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'addProduct' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'addProductWithImages' : ActorMethod<
    [string, string, bigint, string, string, Array<string>, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, string],
    bigint
  >,
  'deleteCustomDesignRequest' : ActorMethod<[bigint], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAboutUs' : ActorMethod<[], string>,
  'getAllCustomDesignRequests' : ActorMethod<[], Array<CustomDesignRequest>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSiteTexts' : ActorMethod<[], Array<[string, string]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomDesignRequest' : ActorMethod<[bigint], CustomDesignRequest>,
  'getHumanRequestCount' : ActorMethod<[], bigint>,
  'getIntegrationSettings' : ActorMethod<[], IntegrationSettings>,
  'getNotificationEmail' : ActorMethod<[], string>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getPortfolioItem' : ActorMethod<[bigint], PortfolioItem>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getShippingInfo' : ActorMethod<[], string>,
  'getSiteText' : ActorMethod<[string], string>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setIntegrationSettings' : ActorMethod<[IntegrationSettings], undefined>,
  'setNotificationEmail' : ActorMethod<[string], undefined>,
  'setSiteText' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAboutUs' : ActorMethod<[string], undefined>,
  'updateCustomDesignRequestStatus' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string, string], undefined>,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    undefined
  >,
  'updateProductWithImages' : ActorMethod<
    [bigint, string, string, bigint, string, string, Array<string>, bigint],
    undefined
  >,
  'updateShippingInfo' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];