/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomDesignRequest {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : string,
  'description' : string,
  'fileUrls' : Array<string>,
  'productType' : string,
  'email' : string,
  'colorPreferences' : string,
  'chatEscalation' : boolean,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'trackingNumber' : string,
  'createdAt' : string,
  'email' : string,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : bigint, 'quantity' : bigint }
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'clientName' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCustomDesignRequest' : ActorMethod<
    [string, string, string, string, string, Array<string>, string, boolean],
    bigint
  >,
  'addPortfolioItem' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'addProduct' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'createOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, string],
    bigint
  >,
  'deleteCustomDesignRequest' : ActorMethod<[bigint], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAboutUs' : ActorMethod<[], string>,
  'getAllCustomDesignRequests' : ActorMethod<[], Array<CustomDesignRequest>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCustomDesignRequest' : ActorMethod<[bigint], CustomDesignRequest>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getPortfolioItem' : ActorMethod<[bigint], PortfolioItem>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getShippingInfo' : ActorMethod<[], string>,
  'updateAboutUs' : ActorMethod<[string], undefined>,
  'updateCustomDesignRequestStatus' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string, string], undefined>,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    undefined
  >,
  'updateShippingInfo' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];